# Generated by Django 4.2.2 on 2024-02-13 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name="Status",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_Status",
                    models.CharField(blank=True, default="", max_length=100),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AllProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "product_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "phon_number",
                    models.CharField(
                        blank=True, default="phon_number", max_length=10, null=True
                    ),
                ),
                (
                    "product_detail",
                    models.TextField(blank=True, default="No description", null=True),
                ),
                (
                    "product_size",
                    models.CharField(
                        blank=True, default="Default Size", max_length=200, null=True
                    ),
                ),
                (
                    "product_statustype",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("พร้อมเช่า", "พร้อมเช่า"),
                            ("ไม่พร้อมเช่า", "ไม่พร้อมเช่า"),
                        ],
                        default=" ",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "product_location",
                    models.CharField(default="location", max_length=200),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        default="broken_image.png",
                        null=True,
                        upload_to="Parcel",
                    ),
                ),
                (
                    "product_status",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shop.status",
                    ),
                ),
            ],
        ),
    ]
