# Generated by Django 4.2.2 on 2023-12-20 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="allproduct",
            old_name="product_id",
            new_name="id",
        ),
    ]
