# Generated by Django 4.2.2 on 2023-12-14 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AllProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_name", models.CharField(max_length=200)),
                ("product_price", models.CharField(max_length=200)),
                ("product_detail", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
