# Generated by Django 4.2.2 on 2024-02-28 16:27

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="sell_buy",
            new_name="SellBuy",
        ),
    ]
