# Generated by Django 4.2.2 on 2024-02-13 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="allproduct",
            name="product_statustype",
            field=models.CharField(
                blank=True,
                choices=[("พร้อมเช่า", "พร้อมเช่า"), ("ไม่พร้อมเช่า", "ไม่พร้อมเช่า")],
                max_length=200,
                null=True,
            ),
        ),
    ]
