# Generated by Django 4.2.2 on 2023-12-20 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0002_rename_product_id_allproduct_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Status",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_Status",
                    models.CharField(blank=True, default="", max_length=100),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="allproduct",
            name="product_price",
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name="allproduct",
            name="product_status",
            field=models.ForeignKey(
                blank=True,
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="shop.status",
            ),
        ),
    ]
