# Generated by Django 4.2.2 on 2024-02-28 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0002_rename_sell_buy_sellbuy"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SellBuy",
        ),
    ]
