# Generated by Django 4.2.2 on 2024-02-13 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0002_alter_allproduct_product_statustype"),
    ]

    operations = [
        migrations.AlterField(
            model_name="allproduct",
            name="product_statustype",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
