# Generated by Django 4.2.2 on 2023-12-14 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0002_allproduct"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="allproduct",
            name="id",
        ),
        migrations.AlterField(
            model_name="allproduct",
            name="product_price",
            field=models.IntegerField(
                max_length=200, primary_key=True, serialize=False
            ),
        ),
    ]
