# Generated by Django 4.2.2 on 2023-12-18 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0003_remove_allproduct_id_alter_allproduct_product_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="allproduct",
            name="img_product",
            field=models.ImageField(blank=True, null=True, upload_to="product_images"),
        ),
    ]
