# Generated by Django 4.2.2 on 2023-12-18 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0004_allproduct_img_product"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="allproduct",
            name="img_product",
        ),
        migrations.CreateModel(
            name="img_product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "img",
                    models.ImageField(
                        blank=True, null=True, upload_to="product_images"
                    ),
                ),
                (
                    "AllProduct",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="shop.allproduct",
                    ),
                ),
            ],
        ),
    ]
