# Generated by Django 4.2.2 on 2023-12-18 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0005_remove_allproduct_img_product_img_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="allproduct",
            name="img",
            field=models.ImageField(blank=True, null=True, upload_to="product_images"),
        ),
        migrations.AddField(
            model_name="allproduct",
            name="product_size",
            field=models.CharField(default="Default Size", max_length=200),
        ),
        migrations.AddField(
            model_name="allproduct",
            name="product_status",
            field=models.CharField(default="Default status", max_length=200),
        ),
        migrations.AlterField(
            model_name="allproduct",
            name="product_detail",
            field=models.TextField(default="No description"),
        ),
        migrations.AlterField(
            model_name="allproduct",
            name="product_price",
            field=models.IntegerField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name="img_product",
        ),
    ]
