# Generated by Django 4.2.2 on 2023-12-20 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0005_alter_allproduct_product_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="allproduct",
            name="statustype",
            field=models.CharField(
                choices=[("พร้อมเช่า", "พร้อมเช่า"), ("ไม่พร้อมเช่า", "ไม่พร้อมเช่า")],
                default=" ",
                max_length=200,
            ),
        ),
    ]
