# Generated by Django 4.2.2 on 2023-12-18 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0006_allproduct_img_allproduct_product_size_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="allproduct",
            name="product_location",
            field=models.CharField(default="location", max_length=200),
        ),
    ]
