# Generated by Django 4.2.2 on 2023-12-20 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0006_allproduct_statustype"),
    ]

    operations = [
        migrations.RenameField(
            model_name="allproduct",
            old_name="statustype",
            new_name="product_statustype",
        ),
        migrations.RemoveField(
            model_name="allproduct",
            name="product_status",
        ),
    ]
