# Generated by Django 4.2.2 on 2023-12-20 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0007_rename_statustype_allproduct_product_statustype_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="allproduct",
            name="image",
            field=models.ImageField(
                blank=True, default="broken_image.png", null=True, upload_to="Parcel"
            ),
        ),
    ]
