# Generated by Django 4.2.2 on 2024-02-26 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0008_cartitem_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartitem",
            name="quantity",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
