# Generated by Django 4.2.2 on 2023-12-21 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0010_alter_allproduct_phon_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="allproduct",
            name="phon_number",
            field=models.CharField(default="phon_number", max_length=10),
        ),
    ]
