# Generated by Django 4.2.2 on 2024-02-28 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0010_cartitem_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="allproduct",
            name="datetime",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
