# Generated by Django 4.2.2 on 2024-02-28 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0012_alter_allproduct_datetime"),
    ]

    operations = [
        migrations.AddField(
            model_name="allproduct",
            name="lastdate",
            field=models.DateField(blank=True, null=True),
        ),
    ]
